import { AlertTriangle, BarChart3, ChevronRight, Plus, SlidersHorizontal } from 'lucide-react'
import type { InventoryItem, ProductionOrder } from '../domain'
import { Bottleneck, CapacityChart, MetricCard, OrderRow, PageHeading, StockRow } from '../components/shared'

export function OverviewScreen({ orders, inventory, onOpenProduction, onOpenStock, selectedLine, setSelectedLine }: { orders: ProductionOrder[]; inventory: InventoryItem[]; onOpenProduction: () => void; onOpenStock: () => void; selectedLine: string; setSelectedLine: (value: string) => void }) {
  return <>
    <PageHeading eyebrow="Terça-feira, 09 de setembro" title="Bom dia, Rafael" description="A fábrica está em ritmo forte. Aqui está o pulso da sua operação." action={<button className="primary-button" onClick={onOpenProduction}><Plus size={17} /> Nova ordem de produção</button>} />
    <div className="alert-banner"><div className="alert-icon"><AlertTriangle size={18} /></div><div><strong>Configuração fiscal requer atenção</strong><span>O regime informado mistura Lucro Real e Simples Nacional. Confirme a opção tributária antes de publicar preços.</span></div><button onClick={() => alert('A parametrização fiscal será aberta na Etapa 3.')}>Revisar agora <ChevronRight size={15} /></button></div>
    <div className="filter-row"><div className="filter-caption"><SlidersHorizontal size={15} /> Visão da operação</div><div className="filter-control"><span>Linha</span><select value={selectedLine} onChange={(event) => setSelectedLine(event.target.value)}><option>Todas as linhas</option><option>Cadeiras Lina</option><option>Banquetas Oca</option></select></div><div className="period-control">Últimos 30 dias <ChevronRight size={14} /></div></div>
    <div className="metric-grid"><MetricCard label="Produção no mês" value="1.248" detail="peças finalizadas" trend="18,4%" direction="up" accent="teal" /><MetricCard label="Ocupação fabril" value="78,6%" detail="capacidade efetiva" trend="6,2%" direction="up" accent="peach" /><MetricCard label="Custo médio / peça" value="R$ 148,50" detail="vs. R$ 153,20 anterior" trend="3,1%" direction="down" accent="cream" /><MetricCard label="Margem de contribuição" value="32,4%" detail="média vendida" trend="2,8%" direction="up" accent="lilac" /></div>
    <div className="dashboard-grid"><section className="panel production-panel"><div className="panel-header"><div><span className="panel-kicker">Acompanhamento ao vivo</span><h2>Ordens em produção</h2></div><button className="text-button" onClick={onOpenProduction}>Ver todas <ChevronRight size={15} /></button></div><div className="order-table"><div className="table-head"><span>Ordem / produto</span><span>Etapa atual</span><span>Avanço</span><span>Entrega</span></div>{orders.slice(0, 3).map((order) => <OrderRow key={order.id} order={order} />)}</div></section><section className="panel stock-panel"><div className="panel-header"><div><span className="panel-kicker">Atenção necessária</span><h2>Saúde do estoque</h2></div><button className="text-button" onClick={onOpenStock}>Abrir estoque <ChevronRight size={15} /></button></div><div className="stock-list">{inventory.map((item) => <StockRow key={item.sku} item={item} />)}</div></section></div>
    <div className="bottom-grid"><section className="panel chart-panel"><div className="panel-header"><div><span className="panel-kicker">Performance industrial</span><h2>Produção x capacidade</h2></div><div className="legend"><span><i className="legend-dot produced" /> Produzido</span><span><i className="legend-dot capacity" /> Capacidade</span></div></div><CapacityChart /></section><section className="panel bottleneck-panel"><div className="panel-header"><div><span className="panel-kicker">Análise de gargalo</span><h2>Fluxo da linha</h2></div><button className="icon-button"><BarChart3 size={17} /></button></div><Bottleneck /></section></div>
  </>
}
