import type { ReactNode } from 'react'
import { ArrowDownRight, ArrowUpRight, BarChart3, Boxes, ChevronRight, Receipt } from 'lucide-react'
import type { InventoryItem, ProductionOrder } from '../domain'
import { inventoryLevel } from '../domain'

export function PageHeading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) {
  return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{action}</div>
}

export function MetricCard({ label, value, detail, trend, direction, accent }: { label: string; value: string; detail: string; trend: string; direction: 'up' | 'down'; accent: string }) {
  return <div className={`metric-card ${accent}`}><div className="metric-top"><span>{label}</span><div className={`trend ${direction}`}>{direction === 'up' ? <ArrowUpRight size={14} /> : <ArrowDownRight size={14} />}{trend}</div></div><strong>{value}</strong><small>{detail}</small></div>
}

export function OrderRow({ order }: { order: ProductionOrder }) { return <div className="order-row"><div className="order-id"><span className="status-marker" data-status={order.status} /><div><strong>{order.id}</strong><small>{order.product} · {order.quantity} un</small></div></div><span className="stage-label">{order.station}</span><div className="progress-wrap"><div className="progress-track"><span style={{ width: `${order.progress}%` }} /></div><small>{order.progress}%</small></div><span className={`status-label ${order.status.toLowerCase().replace(' ', '-')}`}>{order.due}</span></div> }
export function StockRow({ item }: { item: InventoryItem }) { return <div className="stock-row"><div className={`stock-symbol ${item.color}`}><Boxes size={15} /></div><div className="stock-info"><strong>{item.name}</strong><small>{item.sku}</small></div><div className="stock-level"><strong>{item.stock.toLocaleString('pt-BR')} {item.unit}</strong><div className="mini-track"><span className={item.color} style={{ width: `${inventoryLevel(item)}%` }} /></div></div></div> }
export function CapacityChart() { const bars = [62, 68, 70, 76, 72, 84, 79, 88, 81, 91, 86, 94]; return <div className="chart-area"><div className="chart-y"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div><div className="chart-bars">{bars.map((height, index) => <div className="bar-group" key={index}><div className="bar-pair"><span className="bar capacity" style={{ height: `${Math.min(height + 8, 100)}%` }} /><span className="bar produced" style={{ height: `${height}%` }} /></div><small>{['Jun 10', 'Jun 12', 'Jun 14', 'Jun 16', 'Jun 18', 'Jun 20', 'Jun 22', 'Jun 24', 'Jun 26', 'Jun 28', 'Jun 30', 'Jul 02'][index]}</small></div>)}</div></div> }
export function Bottleneck() { return <div className="bottleneck-list"><div className="bottleneck-row"><div><strong>1. Usinagem</strong><small>2,8 min / peça</small></div><span className="bottleneck-value high">92%</span></div><div className="bottleneck-bar"><span style={{ width: '92%' }} /></div><div className="bottleneck-row"><div><strong>2. Montagem</strong><small>2,1 min / peça</small></div><span className="bottleneck-value medium">74%</span></div><div className="bottleneck-bar"><span style={{ width: '74%' }} /></div><div className="bottleneck-row"><div><strong>3. Estofamento</strong><small>1,6 min / peça</small></div><span className="bottleneck-value low">58%</span></div><div className="bottleneck-bar"><span style={{ width: '58%' }} /></div><div className="bottleneck-callout"><BarChart3 size={16} /><span>Adicionar 1 operador em usinagem eleva a capacidade em <strong>14,8%</strong>.</span></div></div> }
export function WipView({ title, description }: { title: string; description: string }) { return <><PageHeading eyebrow="Módulo · WIP" title={title} description={description} /><section className="panel wip-panel"><Receipt size={28} /><h2>Em breve</h2><p>{description}</p></section></> }
